---
- name: Update, upgrade, and reboot system
  hosts: all
  become: yes # This ensures that the playbook runs with sudo privileges
  tasks:

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Upgrade all installed packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot the system
      reboot:
        msg: "Rebooting after upgrade"
        reboot_timeout: 300
