# - name: Wait for Kubernetes API server to become available
#   command: kubectl get nodes
#   register: api_server_check
#   retries: 10
#   delay: 30
#   until: api_server_check.rc == 0
#   delegate_to: "{{ groups['control_plane_nodes'][0] }}"
#   run_once: true

- name: Wait 80s before installing Calico
  ansible.builtin.pause:
    seconds: 80
  delegate_to: "{{ groups['control_plane_nodes'][0] }}"
  run_once: true

- name: Install Tigera Calico
  command: >
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml
    --kubeconfig=/home/k8s/.kube/config
  register: calico_apply
  retries: 5
  delay: 10
  until: calico_apply.rc == 0
  delegate_to: "{{ groups['control_plane_nodes'][0] }}"
  run_once: true
